# --- !Ups

CREATE TABLE PRODUCTS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  TITLE varchar(255),
  COMPANY varchar(255),
  PUBLISH_DATE date,
  LAST_UPDATED date,
  PRIMARY KEY (ID)
);

CREATE TABLE CREATORS_INFO (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255),
  BIRTH_DAY date,
  LAST_UPDATED date,
  PRIMARY KEY (ID)
);

CREATE TABLE CREATORS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255),
  "ROLE" varchar(255),
  PRODUCT_ID bigint(20),
  CREATOR_INFO_ID bigint(20),
  PRIMARY KEY (ID)
);



# --- !Downs

DROP TABLE PRODUCTS;
DROP TABLE CREATORS_INFO;
DROP TABLE CREATORS;